name: Deploy static content to Pages

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures a clean clone

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Cleanup Worktree
        run: git worktree prune  # Cleans up existing worktrees

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # Change from 'develop' to 'gh-pages'
          folder: dist
